### ISSUE TITLE
Python asyncio loop argument deprecated

### ISSUE THREAD

**Issue by artmg** [vanviegen/hue-thief#10]
This is early warning of a feature that will be unavailable in Python 3.10

```python
hue-thief/hue-thief.py:15: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self.q = asyncio.Queue(loop=self.loop)
```

For examples of how to do asyncio queues now please see https://docs.python.org/3.8/library/asyncio-queue.html#examples

Python 3.10 is not likely to be out before the end of 2021 so there's no rush, but if anyone finds themselves inside this code then its something to consider resolving.

**Comment by vanviegen** [comment]
Fixed. Well ahead of end 2021. :-)
