### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by t-8ch** [vanviegen/hue-thief#11]
I would like to reimplement `hue-thief` to make it work with my zigbee sticks.
For that it would be great for `hue-thief` to have an explicitly specified license under which it can be (re)used.

**Comment by vanviegen** [comment]
@t-8ch, sure! I've added a GPL 3 license, to match what is used by the bellows dependency.

Good luck!

**Comment by t-8ch** [comment]
Thanks!
