### ISSUE TITLE
No output, never exists

### ISSUE THREAD

**Issue by mathias-ewald** [vanviegen/hue-thief#12]
Running hue-thief I never see any output nor does the process ever exit. I run the docker container on a host that sees the cc2531 as /dev/ttyACM0:

```
[~] # dmesg | grep ACM
[426686.432044] cdc_acm 2-2:1.0: ttyACM0: USB ACM device
[~] # ls -l /dev/ttyACM0
crw------- 1 admin administrators 166, 0 2020-01-10 09:54 /dev/ttyACM0
[~] #
```

and run the container like this:

`docker run --rm --device=/dev/ttyACM0:/dev/ttyACM0 -it hue-thief:latest python hue-thief/hue-thief.py /dev/ttyACM0``

Inside the container, the device file shows like

```
root@2e13d5a444df:/# ls -l /dev/ttyACM0
crw------- 1 root root 166, 0 Jan 10 10:02 /dev/ttyACM0
```
so from a permissions perspective it should be ok.

After 30min of waiting in front of an empty terminal, I decided to open this issue. I read the troubleshooting section, but I can assure there's no other container using the device.

**Comment by schlauerlauer** [comment]
Same thing happens here.
I am using the conbee2 with just the script.
Permissions shouldn't be the problem.

**Comment by m-a-johnson** [comment]
Script runs but nothing seems to happen. I have tried adjusting permissions and running it on a pi2 and pi3 with no luck. Using the Elelabs Raspberry Pi Shield. Tried just the script, and then tried installing docker and running that way with no luck.

**Comment by schlauerlauer** [comment]
If anyone has the same issue, I caved and bought a Hue Dimmer Remote.
I got the Hue lights to reset without a bridge by pressing on and off simultaneously for about 15 seconds until the light starts flashing. Then unplug the light and plug it back in.
After this I was able to connect the Hue light to Home Assistant with ZHA.

**Comment by zethis** [comment]
Same here, nothing append

**Comment by ultimateguy** [comment]
Try changing the number at the end of the device from 0 to 1. That worked for me.

**Comment by meadowsjared** [comment]
I also ran into this issue and for me it turned out you need to make sure you have the correct device when you run:
`python3 hue-thief /dev/ttyUSB0`
Make sure the `/dev/ttyUSB0` is actually your correct ZigBee device.
If you need to, you can try unplugging it, and check if it's still there, to verify you have the right device. 👍
