### ISSUE TITLE
Bellows upgrade required when using newer firmware on HUSBZB-1

### ISSUE THREAD

**Issue by forkineye** [vanviegen/hue-thief#18]
After upgrading my [HUSBZB-1 firmware](https://github.com/walthowd/husbzb-firmware) to 6.7.8, hue-thief stopped working.  Upgrading [bellows](https://github.com/zigpy/bellows) to 0.34.1 fixed the issue - ```pip3 install bellows==0.34.1```.

**Comment by meadowsjared** [comment]
@forkineye the fix for this is now merged into master 🎉
