### ISSUE TITLE
fails at line 2: No module named 'pure_pcapy'

### ISSUE THREAD

**Issue by freaker2112** [vanviegen/hue-thief#24]
I have ensured that pure_pcapy is installed but it still throws this error

Traceback (most recent call last):
  File "/home/henri/hue-thief/hue-thief.py", line 2, in <module>
    import pure_pcapy
ModuleNotFoundError: No module named 'pure_pcapy'

**Comment by jrb80** [comment]
Ditto. I have the same problem. I tried installing the package separately but now I get different traceback errors.

**Comment by Spatchy** [comment]
I think the solution to this is to install the requirements with sudo if you ran the other installation commands with sudo:

`sudo pip3 install --user -r requirements.txt`

That seemed to solve it for me
