### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by hansmbakker** [vanviegen/hue-thief#4]
On Ubuntu on WSL (probably on all newer ubuntus) I had to install `python3-pip` instead of `python-pip3`

**Comment by wind-rider** [comment]
Also, on Ubuntu on Windows (using WSL) you should do a `sudo apt-get update` and `sudo apt-get upgrade` before installing hue-thief.

Finally, if the usb stick is COM4 in Windows device manager, then it is /dev/ttyS4 in WSL.

**Comment by vanviegen** [comment]
Thanks! Sorry for being slow.
